#! /usr/bin/env python
#  -*- coding: utf-8 -*-
#
# GUI module generated by PAGE version 5.3
#  in conjunction with Tcl version 8.6
#    Jun 15, 2020 09:43:36 AM CEST  platform: Windows NT

import sys

try:
    import Tkinter as tk
except ImportError:
    import tkinter as tk

try:
    import ttk
    py3 = False
except ImportError:
    import tkinter.ttk as ttk
    py3 = True

import dodaj_rezerwacje_support


def vp_start_gui():
    '''Starting point when module is the main routine.'''
    global val, w, root
    root = tk.Tk()
    top = Toplevel1 (root)
    dodaj_rezerwacje_support.init(root, top)
    root.mainloop()


w = None


def create_Toplevel1(rt, *args, **kwargs):
    '''Starting point when module is imported by another module.
       Correct form of call: 'create_Toplevel1(root, *args, **kwargs)' .'''
    global w, w_win, root
    #rt = root
    root = rt
    w = tk.Toplevel (root)
    top = Toplevel1 (w)
    dodaj_rezerwacje_support.init(w, top, *args, **kwargs)
    return (w, top)


def destroy_Toplevel1():
    global w
    w.destroy()
    w = None


class Toplevel1:

    def test(self):
        self.name = self.TEntry1.get()
        self.surname = self.TEntry1_3.get()
        self.month = self.TEntry1_4.get()
        print("Imię: {}".format(self.name))
        print("Nazwisko: {}".format(self.surname))
        print("Miesiąc: {}".format(self.month))
        print(self.TEntry1_5.get())

    def __init__(self, top=None):
        '''This class configures and populates the toplevel window.
           top is the toplevel containing window.'''
        _bgcolor = '#d9d9d9'  # X11 color: 'gray85'
        _fgcolor = '#000000'  # X11 color: 'black'
        _compcolor = '#d9d9d9' # X11 color: 'gray85'
        _ana1color = '#d9d9d9' # X11 color: 'gray85'
        _ana2color = '#ececec' # Closest X11 color: 'gray92'
        self.style = ttk.Style()
        if sys.platform == "win32":
            self.style.theme_use('winnative')
        self.style.configure('.',background=_bgcolor)
        self.style.configure('.',foreground=_fgcolor)
        self.style.configure('.',font="TkDefaultFont")
        self.style.map('.',background=
            [('selected', _compcolor), ('active',_ana2color)])

        top.geometry("1004x683+294+166")
        top.minsize(120, 1)
        top.maxsize(1924, 1061)
        top.resizable(1, 1)
        top.title("New Toplevel")
        top.configure(background="#d9d9d9")

        # var
        self.name = None
        self.surname = None
        self.month = None

        self.Frame1 = tk.Frame(top)
        self.Frame1.place(relx=0.159, rely=0.015, relheight=0.974
                , relwidth=0.833)
        self.Frame1.configure(relief='groove')
        self.Frame1.configure(borderwidth="2")
        self.Frame1.configure(relief="groove")
        self.Frame1.configure(background="#d9d9d9")

        self.TEntry1 = ttk.Entry(self.Frame1)
        self.TEntry1.place(relx=0.12, rely=0.03, relheight=0.047, relwidth=0.211)

        self.TEntry1.configure(takefocus="")
        self.TEntry1.configure(cursor="ibeam")

        self.TEntry1_3 = ttk.Entry(self.Frame1)
        self.TEntry1_3.place(relx=0.12, rely=0.105, relheight=0.047
                , relwidth=0.212)
        self.TEntry1_3.configure(takefocus="")
        self.TEntry1_3.configure(cursor="ibeam")

        self.Label1 = tk.Label(self.Frame1)
        self.Label1.place(relx=0.012, rely=0.03, height=31, width=64)
        self.Label1.configure(background="#d9d9d9")
        self.Label1.configure(disabledforeground="#a3a3a3")
        self.Label1.configure(foreground="#000000")
        self.Label1.configure(text='''Imię''')

        self.Label1_4 = tk.Label(self.Frame1)
        self.Label1_4.place(relx=0.012, rely=0.105, height=31, width=64)
        self.Label1_4.configure(activebackground="#f9f9f9")
        self.Label1_4.configure(activeforeground="black")
        self.Label1_4.configure(background="#d9d9d9")
        self.Label1_4.configure(disabledforeground="#a3a3a3")
        self.Label1_4.configure(foreground="#000000")
        self.Label1_4.configure(highlightbackground="#d9d9d9")
        self.Label1_4.configure(highlightcolor="black")
        self.Label1_4.configure(text='''Nazwisko''')

        self.Label1_5 = tk.Label(self.Frame1)
        self.Label1_5.place(relx=0.012, rely=0.18, height=31, width=64)
        self.Label1_5.configure(activebackground="#f9f9f9")
        self.Label1_5.configure(activeforeground="black")
        self.Label1_5.configure(background="#d9d9d9")
        self.Label1_5.configure(disabledforeground="#a3a3a3")
        self.Label1_5.configure(foreground="#000000")
        self.Label1_5.configure(highlightbackground="#d9d9d9")
        self.Label1_5.configure(highlightcolor="black")
        self.Label1_5.configure(text='''Miesiąc''')

        self.TEntry1_4 = ttk.Entry(self.Frame1)
        self.TEntry1_4.place(relx=0.12, rely=0.18, relheight=0.047
                , relwidth=0.213)
        self.TEntry1_4.configure(takefocus="")
        self.TEntry1_4.configure(cursor="ibeam")

        self.Label1_6 = tk.Label(self.Frame1)
        self.Label1_6.place(relx=0.012, rely=0.256, height=32, width=64)
        self.Label1_6.configure(activebackground="#f9f9f9")
        self.Label1_6.configure(activeforeground="black")
        self.Label1_6.configure(background="#d9d9d9")
        self.Label1_6.configure(disabledforeground="#a3a3a3")
        self.Label1_6.configure(foreground="#000000")
        self.Label1_6.configure(highlightbackground="#d9d9d9")
        self.Label1_6.configure(highlightcolor="black")
        self.Label1_6.configure(text='''Przyjazd''')

        self.TEntry1_5 = ttk.Entry(self.Frame1)
        self.TEntry1_5.place(relx=0.12, rely=0.256, relheight=0.048
                , relwidth=0.213)
        self.TEntry1_5.configure(takefocus="")
        self.TEntry1_5.configure(cursor="ibeam")

        self.TEntry1_5 = ttk.Entry(self.Frame1)
        self.TEntry1_5.place(relx=0.12, rely=0.331, relheight=0.048
                , relwidth=0.213)
        self.TEntry1_5.configure(takefocus="")
        self.TEntry1_5.configure(cursor="ibeam")

        self.TEntry1_5 = ttk.Entry(self.Frame1)
        self.TEntry1_5.place(relx=0.12, rely=0.406, relheight=0.048
                , relwidth=0.213)
        self.TEntry1_5.configure(takefocus="")
        self.TEntry1_5.configure(cursor="ibeam")

        self.TEntry1_5 = ttk.Entry(self.Frame1)
        self.TEntry1_5.place(relx=0.12, rely=0.481, relheight=0.048
                , relwidth=0.213)
        self.TEntry1_5.configure(takefocus="")
        self.TEntry1_5.configure(cursor="ibeam")

        self.TEntry1_5 = ttk.Entry(self.Frame1)
        self.TEntry1_5.place(relx=0.12, rely=0.556, relheight=0.048
                , relwidth=0.213)
        self.TEntry1_5.configure(takefocus="")
        self.TEntry1_5.configure(cursor="ibeam")

        self.TEntry1_5 = ttk.Entry(self.Frame1)
        self.TEntry1_5.place(relx=0.12, rely=0.632, relheight=0.048
                , relwidth=0.213)
        self.TEntry1_5.configure(takefocus="")
        self.TEntry1_5.configure(cursor="ibeam")

        self.Label1_7 = tk.Label(self.Frame1)
        self.Label1_7.place(relx=0.012, rely=0.331, height=32, width=64)
        self.Label1_7.configure(activebackground="#f9f9f9")
        self.Label1_7.configure(activeforeground="black")
        self.Label1_7.configure(background="#d9d9d9")
        self.Label1_7.configure(disabledforeground="#a3a3a3")
        self.Label1_7.configure(foreground="#000000")
        self.Label1_7.configure(highlightbackground="#d9d9d9")
        self.Label1_7.configure(highlightcolor="black")
        self.Label1_7.configure(text='''Wyjazd''')

        self.Label1_7 = tk.Label(self.Frame1)
        self.Label1_7.place(relx=0.012, rely=0.406, height=32, width=64)
        self.Label1_7.configure(activebackground="#f9f9f9")
        self.Label1_7.configure(activeforeground="black")
        self.Label1_7.configure(background="#d9d9d9")
        self.Label1_7.configure(disabledforeground="#a3a3a3")
        self.Label1_7.configure(foreground="#000000")
        self.Label1_7.configure(highlightbackground="#d9d9d9")
        self.Label1_7.configure(highlightcolor="black")
        self.Label1_7.configure(text='''Kwota całk''')

        self.Label1_7 = tk.Label(self.Frame1)
        self.Label1_7.place(relx=0.012, rely=0.481, height=32, width=64)
        self.Label1_7.configure(activebackground="#f9f9f9")
        self.Label1_7.configure(activeforeground="black")
        self.Label1_7.configure(background="#d9d9d9")
        self.Label1_7.configure(disabledforeground="#a3a3a3")
        self.Label1_7.configure(foreground="#000000")
        self.Label1_7.configure(highlightbackground="#d9d9d9")
        self.Label1_7.configure(highlightcolor="black")
        self.Label1_7.configure(text='''Kwota ra''')

        self.Label1_7 = tk.Label(self.Frame1)
        self.Label1_7.place(relx=0.012, rely=0.556, height=32, width=64)
        self.Label1_7.configure(activebackground="#f9f9f9")
        self.Label1_7.configure(activeforeground="black")
        self.Label1_7.configure(background="#d9d9d9")
        self.Label1_7.configure(disabledforeground="#a3a3a3")
        self.Label1_7.configure(foreground="#000000")
        self.Label1_7.configure(highlightbackground="#d9d9d9")
        self.Label1_7.configure(highlightcolor="black")
        self.Label1_7.configure(text='''Booking''')

        self.Label1_7 = tk.Label(self.Frame1)
        self.Label1_7.place(relx=0.012, rely=0.632, height=32, width=74)
        self.Label1_7.configure(activebackground="#f9f9f9")
        self.Label1_7.configure(activeforeground="black")
        self.Label1_7.configure(background="#d9d9d9")
        self.Label1_7.configure(disabledforeground="#a3a3a3")
        self.Label1_7.configure(foreground="#000000")
        self.Label1_7.configure(highlightbackground="#d9d9d9")
        self.Label1_7.configure(highlightcolor="black")
        self.Label1_7.configure(text='''Booking VAT''')

        self.TEntry1_6 = ttk.Entry(self.Frame1)
        self.TEntry1_6.place(relx=0.12, rely=0.707, relheight=0.048
                , relwidth=0.213)
        self.TEntry1_6.configure(takefocus="")
        self.TEntry1_6.configure(cursor="ibeam")

        self.TEntry1_6 = ttk.Entry(self.Frame1)
        self.TEntry1_6.place(relx=0.12, rely=0.782, relheight=0.048
                , relwidth=0.213)
        self.TEntry1_6.configure(takefocus="")
        self.TEntry1_6.configure(cursor="ibeam")

        self.Label1_8 = tk.Label(self.Frame1)
        self.Label1_8.place(relx=0.012, rely=0.707, height=32, width=84)
        self.Label1_8.configure(activebackground="#f9f9f9")
        self.Label1_8.configure(activeforeground="black")
        self.Label1_8.configure(background="#d9d9d9")
        self.Label1_8.configure(disabledforeground="#a3a3a3")
        self.Label1_8.configure(foreground="#000000")
        self.Label1_8.configure(highlightbackground="#d9d9d9")
        self.Label1_8.configure(highlightcolor="black")
        self.Label1_8.configure(text='''Podatek miejski''')

        self.Label1_8 = tk.Label(self.Frame1)
        self.Label1_8.place(relx=0.012, rely=0.782, height=32, width=74)
        self.Label1_8.configure(activebackground="#f9f9f9")
        self.Label1_8.configure(activeforeground="black")
        self.Label1_8.configure(background="#d9d9d9")
        self.Label1_8.configure(disabledforeground="#a3a3a3")
        self.Label1_8.configure(foreground="#000000")
        self.Label1_8.configure(highlightbackground="#d9d9d9")
        self.Label1_8.configure(highlightcolor="black")
        self.Label1_8.configure(text='''Koszty''')

        self.TEntry1_7 = ttk.Entry(self.Frame1)
        self.TEntry1_7.place(relx=0.12, rely=0.857, relheight=0.048
                , relwidth=0.213)
        self.TEntry1_7.configure(takefocus="")
        self.TEntry1_7.configure(cursor="ibeam")

        self.TEntry1_7 = ttk.Entry(self.Frame1)
        self.TEntry1_7.place(relx=0.12, rely=0.932, relheight=0.048
                , relwidth=0.213)
        self.TEntry1_7.configure(takefocus="")
        self.TEntry1_7.configure(cursor="ibeam")

        self.Label1_8 = tk.Label(self.Frame1)
        self.Label1_8.place(relx=0.012, rely=0.857, height=32, width=74)
        self.Label1_8.configure(activebackground="#f9f9f9")
        self.Label1_8.configure(activeforeground="black")
        self.Label1_8.configure(background="#d9d9d9")
        self.Label1_8.configure(disabledforeground="#a3a3a3")
        self.Label1_8.configure(foreground="#000000")
        self.Label1_8.configure(highlightbackground="#d9d9d9")
        self.Label1_8.configure(highlightcolor="black")
        self.Label1_8.configure(text='''Prezent''')

        self.Label1_8 = tk.Label(self.Frame1)
        self.Label1_8.place(relx=0.012, rely=0.932, height=32, width=74)
        self.Label1_8.configure(activebackground="#f9f9f9")
        self.Label1_8.configure(activeforeground="black")
        self.Label1_8.configure(background="#d9d9d9")
        self.Label1_8.configure(disabledforeground="#a3a3a3")
        self.Label1_8.configure(foreground="#000000")
        self.Label1_8.configure(highlightbackground="#d9d9d9")
        self.Label1_8.configure(highlightcolor="black")
        self.Label1_8.configure(text='''Sprzątanie''')

        self.Label1_8 = tk.Label(self.Frame1)
        self.Label1_8.place(relx=0.347, rely=0.03, height=32, width=74)
        self.Label1_8.configure(activebackground="#f9f9f9")
        self.Label1_8.configure(activeforeground="black")
        self.Label1_8.configure(background="#d9d9d9")
        self.Label1_8.configure(disabledforeground="#a3a3a3")
        self.Label1_8.configure(foreground="#000000")
        self.Label1_8.configure(highlightbackground="#d9d9d9")
        self.Label1_8.configure(highlightcolor="black")
        self.Label1_8.configure(text='''Apartament''')

        self.Label1_8 = tk.Label(self.Frame1)
        self.Label1_8.place(relx=0.347, rely=0.105, height=32, width=74)
        self.Label1_8.configure(activebackground="#f9f9f9")
        self.Label1_8.configure(activeforeground="black")
        self.Label1_8.configure(background="#d9d9d9")
        self.Label1_8.configure(disabledforeground="#a3a3a3")
        self.Label1_8.configure(foreground="#000000")
        self.Label1_8.configure(highlightbackground="#d9d9d9")
        self.Label1_8.configure(highlightcolor="black")
        self.Label1_8.configure(text='''Depozyt''')

        self.Label1_8 = tk.Label(self.Frame1)
        self.Label1_8.place(relx=0.347, rely=0.18, height=32, width=74)
        self.Label1_8.configure(activebackground="#f9f9f9")
        self.Label1_8.configure(activeforeground="black")
        self.Label1_8.configure(background="#d9d9d9")
        self.Label1_8.configure(cursor="fleur")
        self.Label1_8.configure(disabledforeground="#a3a3a3")
        self.Label1_8.configure(foreground="#000000")
        self.Label1_8.configure(highlightbackground="#d9d9d9")
        self.Label1_8.configure(highlightcolor="black")
        self.Label1_8.configure(text='''Dokument''')

        self.TEntry1_9 = ttk.Entry(self.Frame1)
        self.TEntry1_9.place(relx=0.455, rely=0.03, relheight=0.047
                , relwidth=0.212)
        self.TEntry1_9.configure(takefocus="")
        self.TEntry1_9.configure(cursor="ibeam")

        self.TEntry1_10 = ttk.Entry(self.Frame1)
        self.TEntry1_10.place(relx=0.455, rely=0.105, relheight=0.047
                , relwidth=0.212)
        self.TEntry1_10.configure(takefocus="")
        self.TEntry1_10.configure(cursor="ibeam")

        self.TEntry1_11 = ttk.Entry(self.Frame1)
        self.TEntry1_11.place(relx=0.455, rely=0.18, relheight=0.047
                , relwidth=0.212)
        self.TEntry1_11.configure(takefocus="")
        self.TEntry1_11.configure(cursor="ibeam")

        self.TEntry1_12 = ttk.Entry(self.Frame1)
        self.TEntry1_12.place(relx=0.455, rely=0.256, relheight=0.047
                , relwidth=0.212)
        self.TEntry1_12.configure(takefocus="")
        self.TEntry1_12.configure(cursor="ibeam")

        self.Label1_9 = tk.Label(self.Frame1)
        self.Label1_9.place(relx=0.347, rely=0.256, height=32, width=74)
        self.Label1_9.configure(activebackground="#f9f9f9")
        self.Label1_9.configure(activeforeground="black")
        self.Label1_9.configure(background="#d9d9d9")
        self.Label1_9.configure(disabledforeground="#a3a3a3")
        self.Label1_9.configure(foreground="#000000")
        self.Label1_9.configure(highlightbackground="#d9d9d9")
        self.Label1_9.configure(highlightcolor="black")
        self.Label1_9.configure(text='''Opłacone?''')

        self.TEntry1_10 = ttk.Entry(self.Frame1)
        self.TEntry1_10.place(relx=0.455, rely=0.331, relheight=0.047
                , relwidth=0.213)
        self.TEntry1_10.configure(takefocus="")
        self.TEntry1_10.configure(cursor="ibeam")

        self.Label1_10 = tk.Label(self.Frame1)
        self.Label1_10.place(relx=0.347, rely=0.331, height=32, width=74)
        self.Label1_10.configure(activebackground="#f9f9f9")
        self.Label1_10.configure(activeforeground="black")
        self.Label1_10.configure(background="#d9d9d9")
        self.Label1_10.configure(disabledforeground="#a3a3a3")
        self.Label1_10.configure(foreground="#000000")
        self.Label1_10.configure(highlightbackground="#d9d9d9")
        self.Label1_10.configure(highlightcolor="black")
        self.Label1_10.configure(text='''Dopłata''')

        self.Home = tk.Button(top)
        self.Home.place(relx=0.01, rely=0.015, height=34, width=137)
        self.Home.configure(activebackground="#ececec")
        self.Home.configure(activeforeground="#000000")
        self.Home.configure(background="#d9d9d9")
        self.Home.configure(disabledforeground="#a3a3a3")
        self.Home.configure(foreground="#000000")
        self.Home.configure(highlightbackground="#d9d9d9")
        self.Home.configure(highlightcolor="black")
        self.Home.configure(pady="0")
        self.Home.configure(text='''Wczytaj''')

        self.Reservation = tk.Button(top)
        self.Reservation.place(relx=0.01, rely=0.088, height=34, width=137)
        self.Reservation.configure(activebackground="#ececec")
        self.Reservation.configure(activeforeground="#000000")
        self.Reservation.configure(background="#d9d9d9")
        self.Reservation.configure(disabledforeground="#a3a3a3")
        self.Reservation.configure(foreground="#000000")
        self.Reservation.configure(highlightbackground="#d9d9d9")
        self.Reservation.configure(highlightcolor="black")
        self.Reservation.configure(pady="0")
        self.Reservation.configure(text='''Zapisz''', command=self.test)

        self.Button1_2 = tk.Button(top)
        self.Button1_2.place(relx=0.01, rely=0.161, height=34, width=137)
        self.Button1_2.configure(activebackground="#ececec")
        self.Button1_2.configure(activeforeground="#000000")
        self.Button1_2.configure(background="#d9d9d9")
        self.Button1_2.configure(disabledforeground="#a3a3a3")
        self.Button1_2.configure(foreground="#000000")
        self.Button1_2.configure(highlightbackground="#d9d9d9")
        self.Button1_2.configure(highlightcolor="black")
        self.Button1_2.configure(pady="0")
        self.Button1_2.configure(text='''Anuluj''')




if __name__ == '__main__':
    vp_start_gui()





