#! /usr/bin/env python
#  -*- coding: utf-8 -*-
#
# GUI module generated by PAGE version 5.3
#  in conjunction with Tcl version 8.6
#    Jun 14, 2020 03:45:29 PM CEST  platform: Windows NT

import sys

try:
    import Tkinter as tk
except ImportError:
    import tkinter as tk
    from tkinter import messagebox, ttk
    from tkinter import *

try:
    import ttk
    py3 = False
except ImportError:
    import tkinter.ttk as ttk
    py3 = True

import test_support


def vp_start_gui():
    '''Starting point when module is the main routine.'''
    global val, w, root
    root = tk.Tk()
    top = Toplevel1(root)
    test_support.init(root, top)
    root.mainloop()

w = None


def create_reservation_window():

    def quit():
        msg = tk.messagebox.askquestion('Zamknięcie programu', 'Czy jesteś pewien, że chcesz zamknąć program?',
                                        icon = 'warning')
        if msg == 'yes':
            exit()

    reservation_window = tk.Toplevel(root)
    reservation_window.grab_set()
    reservation_window.title("Dodaj nową rezerwację")
    reservation_window.geometry("1024x768")
    reservation_window.minsize(1000, 500)
    reservation_window.maxsize(1924, 1061)
    reservation_window.resizable(1, 1)
    Frame1 = tk.Frame(reservation_window)
    Frame1.place(relx=0.159, rely=0.015, relheight=0.974, relwidth=0.832)
    Frame1.configure(relief='groove')
    Frame1.configure(borderwidth="2")
    Frame1.configure(relief="groove")
    Frame1.configure(background="#d9d9d9")

    Home = ttk.Button(reservation_window, text='''Podstawowe''')
    Home.place(relx=0.01, rely=0.015, height=34, width=137)
    Reservation_button = tk.Button(reservation_window, text='''Dodaj rezerwację''')
    Reservation_button.place(relx=0.01, rely=0.088, height=34, width=137)
    Quit = tk.Button(reservation_window, text='''Zamknij''', command=quit)
    Quit.place(relx=0.01, rely=0.161, height=34, width=137)



def create_Toplevel1(rt, *args, **kwargs):
    '''Starting point when module is imported by another module.
       Correct form of call: 'create_Toplevel1(root, *args, **kwargs)' .'''
    global w, w_win, root
    #rt = root
    root = rt
    w = tk.Toplevel(root)
    top = Toplevel1(w)
    test_support.init(w, top, *args, **kwargs)
    return (w, top)


def destroy_Toplevel1():
    global w
    w.destroy()
    w = None


class Toplevel1():

    def quit(self):
        msg = tk.messagebox.askquestion('Zamknięcie programu', 'Czy jesteś pewien, że chcesz zamknąć program?',
                                        icon = 'warning')
        if msg == 'yes':
            exit()

    def __init__(self, top=None):
        '''This class configures and populates the toplevel window.
           top is the toplevel containing window.'''
        _bgcolor = '#d9d9d9'  # X11 color: 'gray85'
        _fgcolor = '#000000'  # X11 color: 'black'
        _compcolor = '#d9d9d9' # X11 color: 'gray85'
        _ana1color = '#d9d9d9' # X11 color: 'gray85'
        _ana2color = '#ececec' # Closest X11 color: 'gray92'

        top.geometry("1024x768+506+230")
        top.minsize(1000, 500)
        top.maxsize(1924, 1061)
        top.resizable(1, 1)
        top.title("Obsługa rezerwacji mscapartments")
        top.configure(background="#d9d9d9")

        self.Frame1 = tk.Frame(top)
        self.Frame1.place(relx=0.159, rely=0.015, relheight=0.974, relwidth=0.832)
        self.Frame1.configure(relief='groove')
        self.Frame1.configure(borderwidth="2")
        self.Frame1.configure(relief="groove")
        self.Frame1.configure(background="#d9d9d9")

        self.Home = ttk.Button(top, text='''Podstawowe''')
        self.Home.place(relx=0.01, rely=0.015, height=34, width=137)
        self.Reservation_button = tk.Button(top, text='''Dodaj rezerwację''', command=create_reservation_window)
        self.Reservation_button.place(relx=0.01, rely=0.088, height=34, width=137)
        self.Quit = tk.Button(top, text='''Zamknij''', command=self.quit)
        self.Quit.place(relx=0.01, rely=0.161, height=34, width=137)


if __name__ == '__main__':
    vp_start_gui()





